export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";


export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAILURE = "ADMIN_LOGIN_FAILURE";


export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const ADD_TO_BAG = "ADD_TO_BAG";
export const FORM_DATA = "FORM_DATA";